package com.mkyong.web.model;
// Generated Jul 25, 2017 12:48:18 PM by Hibernate Tools 4.3.1


import com.fasterxml.jackson.annotation.JsonIgnore;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Bancos generated by hbm2java
 */
@Entity
@Table(name = "bancos",
         catalog = "monitoreo"
)
public class Bancos implements java.io.Serializable {

    private Integer idbanco;
    private String name;
    private String fiid;
    private Set<Tipotarjeta> tipotarjetas = new HashSet<Tipotarjeta>(0);

    public Bancos() {
    }

    public Bancos(String fiid) {
        this.fiid = fiid;
    }

    public Bancos(String name, String fiid, Set<Tipotarjeta> tipotarjetas) {
        this.name = name;
        this.fiid = fiid;
        this.tipotarjetas = tipotarjetas;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "idbanco", unique = true, nullable = false)
    public Integer getIdbanco() {
        return this.idbanco;
    }

    public void setIdbanco(Integer idbanco) {
        this.idbanco = idbanco;
    }

    @Column(name = "name", length = 25)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "fiid", nullable = false, length = 25)
    public String getFiid() {
        return this.fiid;
    }

    public void setFiid(String fiid) {
        this.fiid = fiid;
    }

@ManyToMany(fetch=FetchType.EAGER)
    @JoinTable(name="bancos_tipotarjeta", catalog="monitoreo", joinColumns = { 
        @JoinColumn(name="idbanco", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="idttarjeta", nullable=false, updatable=false) })
    public Set<Tipotarjeta> getTipotarjetas() {
        return this.tipotarjetas;
    }

    public void setTipotarjetas(Set<Tipotarjeta> tipotarjetas) {
        this.tipotarjetas = tipotarjetas;
    }




}


