package com.mkyong.web.model;
// Generated 27/06/2017 05:46:13 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Configuracion generated by hbm2java
 */
@Entity
@Table(name="configuracion"
    ,catalog="monitoreo"
)
public class Configuracion  implements java.io.Serializable {


     private Integer idC;
     private String campo;
     private String valor;

    public Configuracion() {
    }

    public Configuracion(String campo, String valor) {
       this.campo = campo;
       this.valor = valor;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idC", nullable=false)
    public Integer getIdC() {
        return this.idC;
    }
    
    public void setIdC(Integer idC) {
        this.idC = idC;
    }

    
    @Column(name="campo", nullable=false, length=20)
    public String getCampo() {
        return this.campo;
    }
    
    public void setCampo(String campo) {
        this.campo = campo;
    }

    
    @Column(name="valor", nullable=false, length=20)
    public String getValor() {
        return this.valor;
    }
    
    public void setValor(String valor) {
        this.valor = valor;
    }




}


