package com.mkyong.web.model;
// Generated Jul 25, 2017 12:48:18 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Eventos generated by hbm2java
 */
@Entity
@Table(name="eventos"
    ,catalog="monitoreo"
)
public class Eventos  implements java.io.Serializable {


     private int id;
     private String title;
     private Date start;
     private Date end;
     private int value;

    public Eventos() {
    }

	
    public Eventos(String title, int value) {
        this.title = title;
        this.value = value;
    }
    public Eventos(String title, Date start, Date end, int value) {
       this.title = title;
       this.start = start;
       this.end = end;
       this.value = value;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="title", nullable=false, length=20)
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="start", length=10)
    public Date getStart() {
        return this.start;
    }
    
    public void setStart(Date start) {
        this.start = start;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="end", length=10)
    public Date getEnd() {
        return this.end;
    }
    
    public void setEnd(Date end) {
        this.end = end;
    }

    
    @Column(name="value", nullable=false)
    public int getValue() {
        return this.value;
    }
    
    public void setValue(int value) {
        this.value = value;
    }




}


