package com.mkyong.web.model;
// Generated Jul 25, 2017 12:48:18 PM by Hibernate Tools 4.3.1


import com.fasterxml.jackson.annotation.JsonIgnore;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Prefijos generated by hbm2java
 */
@Entity
@Table(name="prefijos"
    ,catalog="monitoreo"
)
public class Prefijos  implements java.io.Serializable {


     private Integer idprefijo;
     private Tipotarjeta tipotarjeta;
     private String name;
     private Set<Servicio> servicios = new HashSet<Servicio>(0);

    public Prefijos() {
    }

	
    public Prefijos(Tipotarjeta tipotarjeta) {
        this.tipotarjeta = tipotarjeta;
    }
    public Prefijos(Tipotarjeta tipotarjeta, String name, Set<Servicio> servicios) {
       this.tipotarjeta = tipotarjeta;
       this.name = name;
       this.servicios = servicios;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idprefijo", unique=true, nullable=false)
    public Integer getIdprefijo() {
        return this.idprefijo;
    }
    
    public void setIdprefijo(Integer idprefijo) {
        this.idprefijo = idprefijo;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idttarjeta", nullable=false)
    @JsonIgnore
    public Tipotarjeta getTipotarjeta() {
        return this.tipotarjeta;
    }
    
    public void setTipotarjeta(Tipotarjeta tipotarjeta) {
        this.tipotarjeta = tipotarjeta;
    }

    
    @Column(name="name", length=25)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

@ManyToMany(fetch=FetchType.EAGER)
    @JoinTable(name="prefijos_servicios", catalog="monitoreo", joinColumns = { 
        @JoinColumn(name="idprefijo", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="idservicio", nullable=false, updatable=false) })
    public Set<Servicio> getServicios() {
        return this.servicios;
    }
    
    public void setServicios(Set<Servicio> servicios) {
        this.servicios = servicios;
    }




}


