package com.mkyong.web.model;
// Generated 28/06/2017 12:38:49 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PrsaTxnAceptadas generated by hbm2java
 */
@Entity
@Table(name="prsa_txn_aceptadas"
    ,catalog="transacciones"
)
public class PrsaTxnAceptadas  implements java.io.Serializable {


     private int id;
     private String nombreArchivo;
     private Date fechaProcesoTransac;
     private Date fechaConsumoTransac;
     private double importeTotalTransac;
     private int archNumero;
     private String modoEntradaPos;
     private String codigoRespuestaAut;
     private String redLogica;
     private int estatusTransaccion;
     private String typ;
     private String respCde;
     private String codigoRespuestaIso;
     private Date fechaLiq;
     private int partitionId;
     private int numeroPrsaAdquiriente;
     private int numeroPrsaEmisor;
     private String fiidAdquiriente;
     private String fiidEmisor;

    public PrsaTxnAceptadas() {
    }

    public PrsaTxnAceptadas(int id, String nombreArchivo, Date fechaProcesoTransac, Date fechaConsumoTransac, double importeTotalTransac, int archNumero, String modoEntradaPos, String codigoRespuestaAut, String redLogica, int estatusTransaccion, String typ, String respCde, String codigoRespuestaIso, Date fechaLiq, int partitionId, int numeroPrsaAdquiriente, int numeroPrsaEmisor, String fiidAdquiriente, String fiidEmisor) {
       this.id = id;
       this.nombreArchivo = nombreArchivo;
       this.fechaProcesoTransac = fechaProcesoTransac;
       this.fechaConsumoTransac = fechaConsumoTransac;
       this.importeTotalTransac = importeTotalTransac;
       this.archNumero = archNumero;
       this.modoEntradaPos = modoEntradaPos;
       this.codigoRespuestaAut = codigoRespuestaAut;
       this.redLogica = redLogica;
       this.estatusTransaccion = estatusTransaccion;
       this.typ = typ;
       this.respCde = respCde;
       this.codigoRespuestaIso = codigoRespuestaIso;
       this.fechaLiq = fechaLiq;
       this.partitionId = partitionId;
       this.numeroPrsaAdquiriente = numeroPrsaAdquiriente;
       this.numeroPrsaEmisor = numeroPrsaEmisor;
       this.fiidAdquiriente = fiidAdquiriente;
       this.fiidEmisor = fiidEmisor;
    }
   
     @Id 

    
    @Column(name="ID", nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="NOMBRE_ARCHIVO", nullable=false, length=20)
    public String getNombreArchivo() {
        return this.nombreArchivo;
    }
    
    public void setNombreArchivo(String nombreArchivo) {
        this.nombreArchivo = nombreArchivo;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="FECHA_PROCESO_TRANSAC", nullable=false, length=19)
    public Date getFechaProcesoTransac() {
        return this.fechaProcesoTransac;
    }
    
    public void setFechaProcesoTransac(Date fechaProcesoTransac) {
        this.fechaProcesoTransac = fechaProcesoTransac;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="FECHA_CONSUMO_TRANSAC", nullable=false, length=19)
    public Date getFechaConsumoTransac() {
        return this.fechaConsumoTransac;
    }
    
    public void setFechaConsumoTransac(Date fechaConsumoTransac) {
        this.fechaConsumoTransac = fechaConsumoTransac;
    }

    
    @Column(name="IMPORTE_TOTAL_TRANSAC", nullable=false, precision=22, scale=0)
    public double getImporteTotalTransac() {
        return this.importeTotalTransac;
    }
    
    public void setImporteTotalTransac(double importeTotalTransac) {
        this.importeTotalTransac = importeTotalTransac;
    }

    
    @Column(name="ARCH_NUMERO", nullable=false)
    public int getArchNumero() {
        return this.archNumero;
    }
    
    public void setArchNumero(int archNumero) {
        this.archNumero = archNumero;
    }

    
    @Column(name="MODO_ENTRADA_POS", nullable=false, length=20)
    public String getModoEntradaPos() {
        return this.modoEntradaPos;
    }
    
    public void setModoEntradaPos(String modoEntradaPos) {
        this.modoEntradaPos = modoEntradaPos;
    }

    
    @Column(name="CODIGO_RESPUESTA_AUT", nullable=false, length=20)
    public String getCodigoRespuestaAut() {
        return this.codigoRespuestaAut;
    }
    
    public void setCodigoRespuestaAut(String codigoRespuestaAut) {
        this.codigoRespuestaAut = codigoRespuestaAut;
    }

    
    @Column(name="RED_LOGICA", nullable=false, length=20)
    public String getRedLogica() {
        return this.redLogica;
    }
    
    public void setRedLogica(String redLogica) {
        this.redLogica = redLogica;
    }

    
    @Column(name="ESTATUS_TRANSACCION", nullable=false)
    public int getEstatusTransaccion() {
        return this.estatusTransaccion;
    }
    
    public void setEstatusTransaccion(int estatusTransaccion) {
        this.estatusTransaccion = estatusTransaccion;
    }

    
    @Column(name="TYP", nullable=false, length=20)
    public String getTyp() {
        return this.typ;
    }
    
    public void setTyp(String typ) {
        this.typ = typ;
    }

    
    @Column(name="RESP_CDE", nullable=false, length=20)
    public String getRespCde() {
        return this.respCde;
    }
    
    public void setRespCde(String respCde) {
        this.respCde = respCde;
    }

    
    @Column(name="CODIGO_RESPUESTA_ISO", nullable=false, length=20)
    public String getCodigoRespuestaIso() {
        return this.codigoRespuestaIso;
    }
    
    public void setCodigoRespuestaIso(String codigoRespuestaIso) {
        this.codigoRespuestaIso = codigoRespuestaIso;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="FECHA_LIQ", nullable=false, length=19)
    public Date getFechaLiq() {
        return this.fechaLiq;
    }
    
    public void setFechaLiq(Date fechaLiq) {
        this.fechaLiq = fechaLiq;
    }

    
    @Column(name="PARTITION_ID", nullable=false)
    public int getPartitionId() {
        return this.partitionId;
    }
    
    public void setPartitionId(int partitionId) {
        this.partitionId = partitionId;
    }

    
    @Column(name="numero_prsa_adquiriente", nullable=false)
    public int getNumeroPrsaAdquiriente() {
        return this.numeroPrsaAdquiriente;
    }
    
    public void setNumeroPrsaAdquiriente(int numeroPrsaAdquiriente) {
        this.numeroPrsaAdquiriente = numeroPrsaAdquiriente;
    }

    
    @Column(name="numero_prsa_emisor", nullable=false)
    public int getNumeroPrsaEmisor() {
        return this.numeroPrsaEmisor;
    }
    
    public void setNumeroPrsaEmisor(int numeroPrsaEmisor) {
        this.numeroPrsaEmisor = numeroPrsaEmisor;
    }

    
    @Column(name="fiid_adquiriente", nullable=false, length=30)
    public String getFiidAdquiriente() {
        return this.fiidAdquiriente;
    }
    
    public void setFiidAdquiriente(String fiidAdquiriente) {
        this.fiidAdquiriente = fiidAdquiriente;
    }

    
    @Column(name="fiid_emisor", nullable=false, length=30)
    public String getFiidEmisor() {
        return this.fiidEmisor;
    }
    
    public void setFiidEmisor(String fiidEmisor) {
        this.fiidEmisor = fiidEmisor;
    }




}


