package com.mkyong.web.model;
// Generated 27/06/2017 05:46:13 PM by Hibernate Tools 4.3.1

import com.fasterxml.jackson.annotation.JsonIgnore;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Roles generated by hbm2java
 */
@Entity
@Table(name = "roles",
         catalog = "monitoreo",
         uniqueConstraints = @UniqueConstraint(columnNames = "name")
)
public class Roles implements java.io.Serializable {

     private Integer id;
     private String name;
     private String displayName;
     private String description;
     private Date createdAt;
     private Date updatedAt;
     private Set<Permissions> permissionses = new HashSet<Permissions>(0);
     private Set<Users> userses = new HashSet<Users>(0);

    public Roles() {
    }

    public Roles(String name, String displayName) {
        this.name = name;
        this.displayName = displayName;
    }

    public Roles(String name, String displayName, String description, Date createdAt, Date updatedAt, Set<Permissions> permissionses, Set<Users> userses) {
       this.name = name;
       this.displayName = displayName;
       this.description = description;
       this.createdAt = createdAt;
       this.updatedAt = updatedAt;
       this.permissionses = permissionses;
       this.userses = userses;
    }
   
    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "name", unique = true, nullable = false)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "display_name", nullable = false)
    public String getDisplayName() {
        return this.displayName;
    }
    
    public void setDisplayName(String displayName) {
        this.displayName = displayName;
    }

    @Column(name = "description")
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "created_at", length = 19)
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "updated_at", length = 19)
    public Date getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

@ManyToMany(fetch=FetchType.EAGER)
    @JoinTable(name = "permission_role", catalog = "monitoreo", joinColumns = {
        @JoinColumn(name = "role_id", nullable = false, updatable = false)}, inverseJoinColumns = {
        @JoinColumn(name = "permission_id", nullable = false, updatable = false)})
    
    
    public Set<Permissions> getPermissionses() {
        return this.permissionses;
    }
    
    public void setPermissionses(Set<Permissions> permissionses) {
        this.permissionses = permissionses;
    }

@ManyToMany(fetch=FetchType.EAGER)
    @JoinTable(name = "role_user", catalog = "monitoreo", joinColumns = {
        @JoinColumn(name = "role_id", nullable = false, updatable = false)}, inverseJoinColumns = {
        @JoinColumn(name = "user_id", nullable = false, updatable = false)})
    
    @JsonIgnore
    public Set<Users> getUserses() {
        return this.userses;
    }
    
    public void setUserses(Set<Users> userses) {
        this.userses = userses;
    }

}
