package com.mkyong.web.model;
// Generated Jul 25, 2017 12:48:18 PM by Hibernate Tools 4.3.1


import com.fasterxml.jackson.annotation.JsonIgnore;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Servicio generated by hbm2java
 */
@Entity
@Table(name="servicio"
    ,catalog="monitoreo"
)
public class Servicio  implements java.io.Serializable {


     private Integer idservicio;
     private String name;
     private String producto;
     private Set<Prefijos> prefijoses = new HashSet<Prefijos>(0);

    public Servicio() {
    }

	
    public Servicio(String name, String producto) {
        this.name = name;
        this.producto = producto;
    }
    public Servicio(String name, String producto, Set<Prefijos> prefijoses) {
       this.name = name;
       this.producto = producto;
       this.prefijoses = prefijoses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idservicio", unique=true, nullable=false)
    public Integer getIdservicio() {
        return this.idservicio;
    }
    
    public void setIdservicio(Integer idservicio) {
        this.idservicio = idservicio;
    }

    
    @Column(name="name", nullable=false, length=10)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="producto", nullable=false, length=20)
    public String getProducto() {
        return this.producto;
    }
    
    public void setProducto(String producto) {
        this.producto = producto;
    }

@ManyToMany(fetch=FetchType.EAGER, mappedBy="servicios")
 @JoinTable(name="prefijos_servicios", catalog="monitoreo", joinColumns = { 
        @JoinColumn(name="idservicio", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="idprefijo", nullable=false, updatable=false) })
 @JsonIgnore
    public Set<Prefijos> getPrefijoses() {
        return this.prefijoses;
    }
    
    public void setPrefijoses(Set<Prefijos> prefijoses) {
        this.prefijoses = prefijoses;
    }




}


