package com.mkyong.web.model;
// Generated Jul 25, 2017 12:48:18 PM by Hibernate Tools 4.3.1


import com.fasterxml.jackson.annotation.JsonIgnore;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tipotarjeta generated by hbm2java
 */
@Entity
@Table(name="tipotarjeta"
    ,catalog="monitoreo"
)
public class Tipotarjeta  implements java.io.Serializable {


     private Integer idttarjeta;
     private String name;
     private Set<Bancos> bancoses = new HashSet<Bancos>(0);
     private Set<Prefijos> prefijoses = new HashSet<Prefijos>(0);

    public Tipotarjeta() {
    }

	
    public Tipotarjeta(String name) {
        this.name = name;
    }
    public Tipotarjeta(String name, Set<Bancos> bancoses, Set<Prefijos> prefijoses) {
       this.name = name;
       this.bancoses = bancoses;
       this.prefijoses = prefijoses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idttarjeta", unique=true, nullable=false)
    public Integer getIdttarjeta() {
        return this.idttarjeta;
    }
    
    public void setIdttarjeta(Integer idttarjeta) {
        this.idttarjeta = idttarjeta;
    }

    
    @Column(name="name", nullable=false, length=10)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    @ManyToMany(fetch=FetchType.EAGER, mappedBy="tipotarjetas")
    @JoinTable(name="bancos_tipotarjeta", catalog="monitoreo", joinColumns = { 
        @JoinColumn(name="idttarjeta", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="idbanco", nullable=false, updatable=false) })
        @JsonIgnore
    public Set<Bancos> getBancoses() {
        return this.bancoses;
    }
    
    public void setBancoses(Set<Bancos> bancoses) {
        this.bancoses = bancoses;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="tipotarjeta")
    public Set<Prefijos> getPrefijoses() {
        return this.prefijoses;
    }
    
    public void setPrefijoses(Set<Prefijos> prefijoses) {
        this.prefijoses = prefijoses;
    }




}


