package com.mkyong.web.model;
// Generated Jul 25, 2017 12:48:18 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Txn generated by hbm2java
 */
@Entity
@Table(name="txn"
    ,catalog="monitoreo"
)
public class Txn  implements java.io.Serializable {


     private Integer id;
     private String prtFilename;
     private Date prtProcDte;
     private String fiidAdquiriente;
     private String fiidEmisor;
     private String redLogicaEmi;
     private String codigoRespuesta;
     private String producto;
     private String ambiente;
     private int tipoTransaccion;
     private int tipoMensaje;
     private String tipoTerminal;
     private int tipoCuenta;
     private String responder;
     private String redLogicaAdq;
     private String entryMode;
     private int medioAcceso;
     private String tokenB4;
     private String tokenB0;

    public Txn() {
    }

    public Txn(String prtFilename, Date prtProcDte, String fiidAdquiriente, String fiidEmisor, String redLogicaEmi, String codigoRespuesta, String producto, String ambiente, int tipoTransaccion, int tipoMensaje, String tipoTerminal, int tipoCuenta, String responder, String redLogicaAdq, String entryMode, int medioAcceso, String tokenB4, String tokenB0) {
       this.prtFilename = prtFilename;
       this.prtProcDte = prtProcDte;
       this.fiidAdquiriente = fiidAdquiriente;
       this.fiidEmisor = fiidEmisor;
       this.redLogicaEmi = redLogicaEmi;
       this.codigoRespuesta = codigoRespuesta;
       this.producto = producto;
       this.ambiente = ambiente;
       this.tipoTransaccion = tipoTransaccion;
       this.tipoMensaje = tipoMensaje;
       this.tipoTerminal = tipoTerminal;
       this.tipoCuenta = tipoCuenta;
       this.responder = responder;
       this.redLogicaAdq = redLogicaAdq;
       this.entryMode = entryMode;
       this.medioAcceso = medioAcceso;
       this.tokenB4 = tokenB4;
       this.tokenB0 = tokenB0;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="prtFilename", nullable=false, length=16)
    public String getPrtFilename() {
        return this.prtFilename;
    }
    
    public void setPrtFilename(String prtFilename) {
        this.prtFilename = prtFilename;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="prtProcDte", nullable=false, length=19)
    public Date getPrtProcDte() {
        return this.prtProcDte;
    }
    
    public void setPrtProcDte(Date prtProcDte) {
        this.prtProcDte = prtProcDte;
    }

    
    @Column(name="fiidAdquiriente", nullable=false, length=30)
    public String getFiidAdquiriente() {
        return this.fiidAdquiriente;
    }
    
    public void setFiidAdquiriente(String fiidAdquiriente) {
        this.fiidAdquiriente = fiidAdquiriente;
    }

    
    @Column(name="fiidEmisor", nullable=false, length=30)
    public String getFiidEmisor() {
        return this.fiidEmisor;
    }
    
    public void setFiidEmisor(String fiidEmisor) {
        this.fiidEmisor = fiidEmisor;
    }

    
    @Column(name="redLogicaEmi", nullable=false, length=30)
    public String getRedLogicaEmi() {
        return this.redLogicaEmi;
    }
    
    public void setRedLogicaEmi(String redLogicaEmi) {
        this.redLogicaEmi = redLogicaEmi;
    }

    
    @Column(name="codigoRespuesta", nullable=false, length=10)
    public String getCodigoRespuesta() {
        return this.codigoRespuesta;
    }
    
    public void setCodigoRespuesta(String codigoRespuesta) {
        this.codigoRespuesta = codigoRespuesta;
    }

    
    @Column(name="producto", nullable=false, length=20)
    public String getProducto() {
        return this.producto;
    }
    
    public void setProducto(String producto) {
        this.producto = producto;
    }

    
    @Column(name="ambiente", nullable=false, length=20)
    public String getAmbiente() {
        return this.ambiente;
    }
    
    public void setAmbiente(String ambiente) {
        this.ambiente = ambiente;
    }

    
    @Column(name="tipoTransaccion", nullable=false)
    public int getTipoTransaccion() {
        return this.tipoTransaccion;
    }
    
    public void setTipoTransaccion(int tipoTransaccion) {
        this.tipoTransaccion = tipoTransaccion;
    }

    
    @Column(name="tipoMensaje", nullable=false)
    public int getTipoMensaje() {
        return this.tipoMensaje;
    }
    
    public void setTipoMensaje(int tipoMensaje) {
        this.tipoMensaje = tipoMensaje;
    }

    
    @Column(name="tipoTerminal", nullable=false, length=20)
    public String getTipoTerminal() {
        return this.tipoTerminal;
    }
    
    public void setTipoTerminal(String tipoTerminal) {
        this.tipoTerminal = tipoTerminal;
    }

    
    @Column(name="tipoCuenta", nullable=false)
    public int getTipoCuenta() {
        return this.tipoCuenta;
    }
    
    public void setTipoCuenta(int tipoCuenta) {
        this.tipoCuenta = tipoCuenta;
    }

    
    @Column(name="responder", nullable=false, length=20)
    public String getResponder() {
        return this.responder;
    }
    
    public void setResponder(String responder) {
        this.responder = responder;
    }

    
    @Column(name="redLogicaAdq", nullable=false, length=20)
    public String getRedLogicaAdq() {
        return this.redLogicaAdq;
    }
    
    public void setRedLogicaAdq(String redLogicaAdq) {
        this.redLogicaAdq = redLogicaAdq;
    }

    
    @Column(name="entryMode", nullable=false, length=20)
    public String getEntryMode() {
        return this.entryMode;
    }
    
    public void setEntryMode(String entryMode) {
        this.entryMode = entryMode;
    }

    
    @Column(name="medioAcceso", nullable=false)
    public int getMedioAcceso() {
        return this.medioAcceso;
    }
    
    public void setMedioAcceso(int medioAcceso) {
        this.medioAcceso = medioAcceso;
    }

    
    @Column(name="tokenB4", nullable=false, length=20)
    public String getTokenB4() {
        return this.tokenB4;
    }
    
    public void setTokenB4(String tokenB4) {
        this.tokenB4 = tokenB4;
    }

    
    @Column(name="TokenB0", nullable=false, length=40)
    public String getTokenB0() {
        return this.tokenB0;
    }
    
    public void setTokenB0(String tokenB0) {
        this.tokenB0 = tokenB0;
    }




}


